name: CI Development
on:
  push:
    branches-ignore:
      - master
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install npm packages
        run: npm i

      - name: Run unit tests
        run: npm run test
